// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5KoYedgZtrE3QccIYuKLvoBdbFJ7wVk',
    appId: '1:256943613795:web:9421cf298a3986c58bd556',
    messagingSenderId: '256943613795',
    projectId: 'appbeyoglu',
    authDomain: 'appbeyoglu.firebaseapp.com',
    storageBucket: 'appbeyoglu.appspot.com',
    measurementId: 'G-YX2M8WH1Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13XAt1HFpA1HBc469uKYnj9yAJKsnBKw',
    appId: '1:256943613795:android:c9b84e1511c1265c8bd556',
    messagingSenderId: '256943613795',
    projectId: 'appbeyoglu',
    storageBucket: 'appbeyoglu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Z5Iy97xhoyUR1fJzxalEW8pfU97Sw0g',
    appId: '1:256943613795:ios:58b6e42058f660618bd556',
    messagingSenderId: '256943613795',
    projectId: 'appbeyoglu',
    storageBucket: 'appbeyoglu.appspot.com',
    androidClientId: '256943613795-3h7u25osv8r2shf6eo108o2itughavij.apps.googleusercontent.com',
    iosClientId: '256943613795-7fko52ge8qlmgdh2odpfpo50c1g8dk2s.apps.googleusercontent.com',
    iosBundleId: 'com.app.acc',
  );

}